baseURL = '/'
defaultContentLanguage = "zh-hans"
defaultContentLanguageInSubdir = false

theme = "hugo-theme-misipage"

[params]

# 多语言配置
[languages]

[languages.en]
contentDir = "content/en"
hasCJKLanguage = true
languageCode = "en"
languageName = "English"
title = 'Misite Bao'
weight = 1

[languages.en.author]
email = "i@misitebao.com"
name = "Misite Bao"
website = "https://misitebao.com/en"

[languages.zh-Hans]

contentDir = "content/zh-Hans"
hasCJKLanguage = true
languageCode = "zh-Hans"
languageName = "简体中文"
title = '米司特包 - 技术服务于进化而非控制'
weight = 2

[languages.zh-Hans.author]
email = "i@misitebao.com"
name = "米司特包"
website = "https://misitebao.com/"
